### ISSUE TITLE
Wiki Typo

### ISSUE THREAD

**Issue by PinkSwitch** [Raidenthequick/yoshisisland-disassembly#10]
On the wiki, game mode 20 is listed starting at address $17A58E, it actually starts at address $17A5AE

**Comment by brunovalads** [comment]
Oh thanks for pointing out, I fixed it in revision [176c758](https://github.com/brunovalads/yoshisisland-disassembly/wiki/Game-Modes/176c758d935e19106a5e1139930effd725fb2a62), every entry is fine now. I noticed some gamemodes don't have labels in the disassembly, it's fine for now eventually I work them out as keep documenting.
