### ISSUE TITLE
Autoscroller data table formatted in a way that's difficult to read

### ISSUE THREAD

**Issue by racknae** [Raidenthequick/yoshisisland-disassembly#8]
Each checkpoint in the autoscroll data is represented by a 3-byte chunk, so why, for most of the table, is it formatted into 4-byte chunks? This makes it needlessly difficult for a user to read the data checkpoint-by-checkpoint. Only autoscroller $1CB is listed in the proper format at the moment.

**Comment by brunovalads** [comment]
Closed with 2006630.
