### ISSUE TITLE
More Sound ID info

### ISSUE THREAD

**Issue by LoveBodhi** [Raidenthequick/yoshisisland-disassembly#9]
Sound 33 is also used for Red Switch Activate.

**Comment by brunovalads** [comment]
I noticed a bunch of sounds need more complete descriptions, as they are re-used in various other places, such as thunder during Prince_Froggy. Feel free to point out any other you can find!
I'm taking the time to properly finish marking "play sound #$XXX" in the remaining spots in the disassembly, then I can analyze it to figure out more sound usages.

**Comment by brunovalads** [comment]
I made [an asm patch providing a Sound Test feature in YI](https://www.smwcentral.net/?p=section&a=details&id=31982), it should make it easier to test sounds, instead of playing the whole game.

**Comment by brunovalads** [comment]
After days of sound triggering, better documenting (https://github.com/brunovalads/yoshisisland-disassembly/commit/fd7ef1dcb59dcc265d4965d4531e8ca4accd3152, https://github.com/brunovalads/yoshisisland-disassembly/commit/7740704f76b8980c3e67add39d3dc57cacb2303e, https://github.com/brunovalads/yoshisisland-disassembly/commit/ded361ddca19b194506dae4a0a96732c16c6f679), and some [nice discoveries](https://twitter.com/brunovalads_/status/1567604067421097987), I consider the Sound ID table done[^1]!
Check the [revision](https://github.com/brunovalads/yoshisisland-disassembly/wiki/Sound-IDs/3645704c1dff5ff06aba08823ec7fe431ef6bfd8), and make sure to comment here if you even find undocummented usages.

[^1]: I still don't know what $7C is supposed to be, it was named "Sluggy the unshaven moving?"
